import re
from typing import Match


def convert_ui_translations(contents: str) -> str:
    """
    Transforms Qt-generated translation calls into standard Gettext calls.

    This function processes the content of a Python file generated by `pyside6-uic` and:
    1. Injects a project-wide `_` translation function import at the top of the file.
    2. Replaces `QCoreApplication.translate("Context", "Message")` with `_("Message")`.
    3. Generates descriptive 'i18n:' comments above each translated string, including
       the widget context and the specific UI field (e.g., 'window title', 'text', 'tool tip')
       being set. These comments are later extracted by Babel to provide context for translators.
    4. Ensures compliance by asserting that no legacy `_translate` calls remain.
    """
    contents = re.sub(
        r"\n", ('\n_ = __import__(__package__.split(".", 1)[0])._\n'), contents, 1
    )

    def repl(m: Match[str]) -> str:
        gd = m.groupdict()
        comment = "{ws}# i18n: Widget: “{widget}”".format(**gd)
        field = gd["field"]
        if field:
            field = " ".join(
                word.lower() for word in re.split(r"([A-Z][a-z_0-9]+)", field) if word
            )
            comment += ", {field}".format(field=field)
        comment += "."
        gd["pre2"] = gd["pre2"] or ""
        return "{comment}\n{ws}{pre1}{pre2}_({msg}".format(comment=comment, **gd)

    contents = re.sub(
        (
            r"(?P<ws> *)(?P<pre1>.*?)(?P<pre2>\.set(?P<field>\w+)\()?"
            r'(?:QCoreApplication\.translate)\("(?P<widget>.*?)",\s*'
            r'(?P<msg>(?:u?"(?:[^"\\]|\\.)*?"\s*)+)'
            r"(?:,\s*None)?"
        ),
        repl,
        contents,
    )
    assert re.search(r"\b_translate\(", contents) is None
    return contents


def remove_ui_autoconnection(contents: str) -> str:
    """
    Removes automatic signal-slot connection calls from the generated UI file.

    Strips `connectSlotsByName` calls to prevent implicit bindings via naming
    conventions. This ensures all connections are explicitly defined for
    improved clarity and maintainability.
    """
    contents = re.sub(
        r"\n\s+QtCore\.QMetaObject\.connectSlotsByName\(\w+\)\n", "\n", contents
    )
    return contents
